fox-it/acquire

- acquire/collector.py
- tests/test_collector.py
> Make collection of non-existent files more clear

- acquire/acquire.py
Embed CAgent SSL artefacts
(DIS-1518)
> Embed CAgent SSL artefacts (DIS-1518)

- acquire/acquire.py
> acquire Sophos/HitmanPRO Quarantined files

- acquire/acquire.py
https://www.mandiant.com/resources/blog/reviewing-macos-unified-logs
> Add Unified Logs folder

- acquire/acquire.py
> Fix issue with comparing float and string in windows-arp-cache

- acquire/acquire.py
> Move Sophos/Hitman quarantines to quarantine-section

- acquire/acquire.py
> Fix Qwinsta

- acquire/acquire.py
- acquire/dynamic/windows/collect.py
- acquire/dynamic/windows/exceptions.py
- acquire/dynamic/windows/handles.py
- acquire/dynamic/windows/named_objects.py
- acquire/dynamic/windows/ntdll.py
- acquire/dynamic/windows/types.py
- tests/test_acquire_command.py
> Add open handles plugin

- acquire/acquire.py
- acquire/collector.py
- tox.ini
> Update style and pin on black v23.1.0

- acquire/acquire.py
- acquire/collector.py
- acquire/crypt.py
- acquire/dynamic/windows/collect.py
- acquire/log.py
- acquire/outputs/dir.py
- acquire/tools/decrypter.py
- tests/test_utils.py
- tox.ini
> Add isort to flake8 linting

- acquire/dynamic/windows/handles.py
> Fix bug in comparison

- acquire/acquire.py
> Collect Windows Program Compatibility Assistant files

- acquire/acquire.py
- acquire/collector.py
- acquire/outputs/base.py
- acquire/outputs/dir.py
- acquire/outputs/tar.py
- acquire/utils.py
- tests/test_collector.py
> Collect proc and sys filesystems

- acquire/acquire.py
Adds the SQLite3-based logs to AV as well.
> Acquire McAfee SQLite-based logs as well

- tox.ini
> Exclude version.py from linting

- acquire/acquire.py
> Collect GPO (Group Policy Objects) History

- acquire/collector.py
- tests/test_collector.py
> Fix missing module name when collecting glob

- tests/test_utils.py
> Skip incompatible unit tests on Windows

- acquire/acquire.py
https://github.com/EricZimmerman/KapeFiles/blob/c2e6c077ca87dc027e3c2b9a0c51ec232fd4205d/Targets/Windows/LNKFilesAndJumpLists.tkape
> Add LNK paths

- acquire/acquire.py
https://learn.microsoft.com/en-us/windows/deployment/update/windows-update-logs
> Add Windows Update related log files

- acquire/acquire.py
> Add IIS plugin to full profile

- acquire/acquire.py
- acquire/collector.py
- acquire/outputs/base.py
- acquire/outputs/dir.py
- acquire/outputs/tar.py
- acquire/utils.py
- acquire/volatilestream.py
- tests/conftest.py
- tests/test_collector.py
- tests/test_outputs_dir.py
- tests/test_outputs_tar.py
> Collect empty directories when the source is volatile

- acquire/acquire.py
> Make acquire Windows paths uniform

- tests/test_collector.py
- tests/test_outputs_dir.py
> Skip failing tests on Windows for now

- acquire/acquire.py
- acquire/utils.py
> Embed Targetd Config

- acquire/acquire.py
> Properly name special NTFS file in the collected output

- acquire/acquire.py
> Add miscellaneous Windows artefacts

- acquire/acquire.py
> Properly acquire virtual NTFS filesystems

- acquire/acquire.py
> Add additional SchedLgU.txt paths

- acquire/acquire.py
> Refactor history module and add cookies for Chrome

- acquire/acquire.py
This PR adds support for the Brave browser. See https://github.com/fox-it/dissect.target/pull/538.
> Add Brave support

- .github/workflows/dissect-ci.yml
- acquire/crypt.py
- pyproject.toml
- tox.ini
> Compatibility with cstruct v4

- acquire/acquire.py
Currently only Carbon Black logs are collected.
> Add an EDR (Endpoint Detection and Response) log collection module

- acquire/acquire.py
- tests/test_gui.py
> Fix shard issue

- acquire/acquire.py
Added the collection of the DataStore of the Windows Update Agent. This PR is linked to the wua_history plugin in the following PR:
https://github.com/fox-it/dissect.target/pull/770
> Added Windows Update Agent's DataStore for collection

- acquire/acquire.py
> Add MacOS and Linux log paths to TeamViewer module

- acquire/acquire.py
Added docker logs, hostname and container configs to acquire and included it in the `FULL` Linux profile
> Add collection of Docker logs

- acquire/acquire.py
Add support for `network` and `applications` module from `dissect.target`.
closes #227
> Add Applications and Network modules
