acquire/acquire.py

Upon failure to open a target, this update checks whether the user is admin/root and displays a hint.
(DIS-1648)

Proposal to improve error handling

---

acquire/acquire.py
acquire/crypt.py
acquire/utils.py
tests/test_acquire_command.py
tests/test_utils.py

Improve command line argument validation

---

acquire/acquire.py
acquire/collector.py
acquire/utils.py
tests/conftest.py
tests/test_collector.py
tests/test_utils.py

In certain circumstances acquire can encounter its own output files, collecting them is not desired. These are currently the log file and output tar file or output directory.
This can happen in a number of cases:
- devtmpfs is mounted somewhere under /var, some of te symlinks under /dev/fd will point to the acquire files,
- acquire is executed from one of the directories that will be collected and the output directory is not changed from the default,
- the output directory is set to a (sub-)drictory that will be collected.
(DIS-1785)

Prevent collection of acquire's own output files

---

acquire/acquire.py

The module contains browser history paths found on Linux distributions, but the module is not used by any Linux profile 
* https://github.com/fox-it/acquire/blob/main/acquire/acquire.py#L1106-L1150
* https://github.com/fox-it/acquire/blob/main/acquire/acquire.py#L1215-L1244

Add Browser history to Linux (full profile)

---

acquire/acquire.py

For a user policy setting, the database is stored in the following location: `C:\Users%username%\AppData\Local\Microsoft\Group Policy\History`
https://learn.microsoft.com/en-us/troubleshoot/windows-server/group-policy/remove-this-item-if-it-is-no-longer-applied-option

Add User Group Policy path

---

acquire/acquire.py

Refine integration Targetd/Acquire

---

acquire/acquire.py
acquire/collector.py

References 
* https://github.com/fox-it/dissect.target/blob/b6ea46e2ed95321440df6c8c6b65803af06da859/dissect/target/plugins/os/unix/bsd/osx/_os.py#L21
* https://github.com/ForensicArtifacts/artifacts/blob/ae1baa1675e43d199721dd2e97678ac56330b5a1/data/macos.yaml#L97-L106

Add MacOS applications path

---

acquire/acquire.py

Used by Dissect Target to find configured IP-addresses.
https://github.com/fox-it/dissect.target/blob/b6ea46e2ed95321440df6c8c6b65803af06da859/dissect/target/plugins/os/unix/bsd/osx/_os.py#L50-L56

Add OSX DHCP settings

---

acquire/acquire.py
acquire/utils.py

Allows for skipping parent collection when running with `--children`.

Add --skip-parent argument

---

acquire/acquire.py
acquire/log.py

Add targetd service flag to config

---

acquire/acquire.py

I've been working on the dissect.target implementation for the SearchIndex forensic artifact. (https://www.aon.com/cyber-solutions/aon_cyber_labs/windows-search-index-the-forensic-artifact-youve-been-searching-for/)
Adding the default directory for the important databases to acquire to collect the relevant files.

Add default SearchIndex database file location

---

acquire/acquire.py
acquire/collector.py
acquire/utils.py
tests/test_utils.py

Fix deduplication of collected files on case insensitive targets

---

acquire/collector.py
acquire/utils.py
tests/test_collector.py
tests/test_utils.py

Required for https://github.com/fox-it/dissect.target/pull/497.
Allows `dissect.target` to support acquire outputs for systems that have a non-default sysvol drive letter.

Map all Windows sysvol paths to their drive letter

---

acquire/acquire.py
acquire/utils.py
tests/test_utils.py

Add `output-file` command line argument

---

acquire/acquire.py
acquire/collector.py
acquire/utils.py
tests/conftest.py
tests/test_collector.py
tests/test_utils.py

When paths contain intermediate symlinks, these intermediate symlinks are collected instead of collecting the unresolved path as is. De-duplication between sysvol and it's equivalent drive letter path is done properly.
Collecting of special files (e.g. MFT, Recyclebin etc.) is properly abstracted.
(DIS-1222)

New collection and de-duplication logic

---

acquire/acquire.py
acquire/uploaders/plugin.py
acquire/utils.py

Improve logging successful and failed acquire runs

---

acquire/acquire.py

Acquire part for https://github.com/fox-it/dissect.target/pull/540. For now, only collect the Windows 11 notepad tab directory, but this may of course be extended. Also added it to the `full` profile.

Add collection of notepad tab directories

---

acquire/outputs/zip.py

The zip outputs of acquire ignored the compression type given, due to the use of zipfile.ZipInfo without supplying a compression type to these objects. This PR fixes that.
I also changed the compression type to deflate, as this is better supported throughout other forensic tools (read: tools we use ourselves to process acquire collects)

Fix compression in zip outputs when compress option is supplied

---

acquire/acquire.py
acquire/outputs/__init__.py
acquire/outputs/tar.py
acquire/outputs/zip.py
acquire/utils.py
tests/test_outputs_tar.py
tests/test_outputs_zip.py
tests/test_utils.py

Make `tar` and `zip` compression output configurable by supplying a `--compress-method` argument as mentioned in #182 
Additionally, some tests have been adjusted to account for this change.

Make acquire compression configurable

---

.gitignore
acquire/utils.py
tests/test_utils.py

_Note: There are failing CI checks unrelated to this pr.  After CI is fixed, this PR can be re-reviewed._  
Make error messages concerning  `output-file` consistent with the name of the flag.
extra: 
- git ignore acquire artifacts when running the package from the root. 
- fully git ignore the .tox directory
closes #169

Fix inconsistent error messages involving `output-file`

---

acquire/utils.py

This adds support for the `-K` and `-Kv` arguments (just like `target-*`) to support Acquire on BitLocker and LUKS encrypted targets.

Add BitLocker and LUKS support to Acquire

---

acquire/acquire.py

Acquire device list

---

acquire/collector.py

dissect.target's NotADirectoryError and FileNotFoundError are now proper subclasses of the std.NotADirectoryError and std.FileNotFoundError and by this a subclass of OSError, so they should be treated as such.

Fix regression in OSError handling logic

---

acquire/acquire.py

Make acquire more robust against missing collection profiles

---

acquire/acquire.py

Server Editions of Windows have the capability to support per user search databases (Windows Search database roaming). The artefacts appear to be in the same format as the ones stored in the standard folder but split out per user. Verified on Server 2022 and Server 2025 using the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Search: "EnablePerUserCatalog"=dword:00000001 registry key.

Add collection of individual user search indexes on Windows

---

acquire/tools/decrypter.py

Noticed this while browsing this file looking for a way to do something.

Return the exit code instead of exiting in main

---

acquire/acquire.py

Collect /proc/net on default volatile collection

---

acquire/acquire.py

I had already added a snap installation path to parse Brave browser history in another [PR for dissect.target](https://github.com/fox-it/dissect.target/pull/1031). This PR makes sure that acquire will collect it as well.

Added brave history path when installed with snap

---

acquire/acquire.py

Added some additional paths for AV collections.

Added paths for AV collection

---

acquire/acquire.py
pyproject.toml
tests/_docs/index.rst
tests/test_misc_users.py

For discussion see https://github.com/fox-it/dissect.target/pull/1085. Changelog should include the change of argument names as well.

Rename OSX to macOS

---

acquire/acquire.py

This PR changes the Anydesk configuration to collect additional Anydesk files if possible. This includes the filetransfer_trace.txt files for which Dissect.Target support was recently created.
Resolves: #232

Collect additional Anydesk files Win/Linux/Mac

---

acquire/acquire.py

This PR adds the paths for RustDesk to be collected by Acquire and closes #207.

Collect RustDesk log files Win/Linux/Mac

---

acquire/acquire.py
acquire/utils.py

As discussed internally, we disabled automatic nfs mounting.
This PR adds a flag to enable mounting of any found nfs shares

Add flag to enable nfs

---

acquire/acquire.py

Fix module disable

---

acquire/acquire.py

These logs are very useful to detect ToolShell exploitation events

Add SharePoint Server logs

---

acquire/acquire.py

closes #258
closes #155
closes #180
Initially just wanted to add RustDesk paths, but noticed some easy to fix issues so added those as well. 
Looking at the [RustDesk Github Page](https://github.com/rustdesk/rustdesk/wiki/FAQ), I noticed that some files would not get collected with the current config. This PR should fix that.

Add NTFS and RemoteAccess paths

---

acquire/acquire.py

Infer path of bootbanks
